// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
// Stimulusコントローラ群をまとめて登録・管理するための「エントリーポイント」 の役割
// ./controllers フォルダ内にある複数のStimulusコントローラを一括で読み込んで、
// StimulusのApplication（application.js 内のもの）に登録する処理をする

// controllers/	: StimulusのコントローラJSを置く場所
// index.js	: それらコントローラをStimulusに登録する設定ファイル

import { application } from "./application"

import HelloController from "./hello_controller"
import ImagePreviewController from "./image_preview_controller"  // ここを追加

application.register("hello", HelloController)
application.register("image-preview", ImagePreviewController)   // ここを追加

