# fly.toml app configuration file generated for koreuma-web on 2025-07-29T18:51:00+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'koreuma-web'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile.fly'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
